version: '3.5'
services:
  weatherapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: weather-app-docker-compose
    ports:
      - 8080
    networks:
      - network1
    scale: 2
 
networks:
  network1: